
# spring
spring :
  mvc :
    view :
      prefix : /jsp/
      suffix : jsp

# server
server:
  port: 8081
  servlet:
    context-path: /aaa

hello:
  msg: 吧啦啦小魔仙

valueTest :
  url :
    testHello : 你好帅呀哈哈哈~
    testMe : 哎呀呀









